apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-k8s-demo
  template:
    metadata:
      labels:
        app: go-k8s-demo
    spec:
      containers:
        - name: go-app
          # 此处的 ${IMAGE} 会被云效流水线自动替换为实际构建的镜像地址
          image: crpi-qog7f6f2a152sq41-vpc.cn-shanghai.personal.cr.aliyuncs.com/test20260603/golang:2026061208 
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: imagesecret
---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-demo-svc
spec:
  selector:
    app: go-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
